### ISSUE TITLE
About setting admin privileges

### ISSUE THREAD

**Issue by HK560** [ScureX/Takyon.PlayerVote#10]
Hope that can set admin privileges by player uid.

**Comment by ScureX** [comment]
Hi, as you can see [here](https://github.com/ScureX/Takyon.PlayerVote/projects/1#card-76879200) setting admins with their UID is **already planned** as feature 14. This will likely be **released soon** in **v3.0.0**!

**Comment by HK560** [comment]
ahh i see. appreciate your work!
