### ISSUE TITLE
Negative cmd args crrash server

### ISSUE THREAD

**Issue by xamionex** [ScureX/Takyon.PlayerVote#33]
**Describe the bug**
Probably an arg issue where my boi taky forgot to check.
-1 in vars crashes the server..

**To Reproduce**
!skip -1
(Honestly I forgot the commands but you should still check it out)

**Expected behavior**
Don't crash server ong

**Comment by ScureX** [comment]
this has been fixed in the latest version wym?

**Comment by xamionex** [comment]
> this has been fixed in the latest version wym?

Damn didnt know
