### ISSUE TITLE
!skip does not work on round-based gamemodes

### ISSUE THREAD

**Issue by xia0** [ScureX/Takyon.PlayerVote#36]
**Describe the bug**
Using !skip on round-based gamemodes will start the timer but only end the round, not the map.

**To Reproduce**
1. Map - any
2. Gamemode - round-based e.g. lts, ctf, fastball...
3. Command - !skip
4. Error - no error, map doesn't change

**Expected behavior**
Expect it to start 30 second timer if maps not proposed or 1 second timer if they have followed up by map change.

**Screenshots**

**Release version:**
main branch

**Additional context**

**Comment by ScureX** [comment]
Definetly something to keep in mind. Cant think of an easy fix but would release in the version after 3.1.2 because i want to get those bug-fixes out
